package main

import (
	HosterHost "HosterCore/internal/pkg/hoster/host"
	"os"
)

func setResolvConf() {
	conf, err := HosterHost.GetHostConfig()
	if err != nil {
		log.Error("Failed to read the host config: " + err.Error())
	}

	// Set the resolv.conf
	const file = "/etc/resolv.conf"

	// Set the file contents
	lines := "###########################################\n"
	lines += "## Automatically generated by Hoster     ##\n"
	lines += "## Any modifications will be overwritten ##\n"
	lines += "###########################################\n"
	lines += "\n"
	lines += "search " + conf.DnsSearchDomain + "\n"
	lines += "nameserver 127.0.0.1\n"
	lines += "options ends0 single-request timeout:5\n"
	lines += "\n"

	// Write the file
	err = os.WriteFile(file, []byte(lines), 0644)
	if err != nil {
		log.Error("Failed to write the resolv.conf: " + err.Error())
	}
}
